const Types = {
    SIGN_IN: 'SIGN_IN',
    SIGN_UP: 'SIGN_UP',
    SIGN_OUT: 'SIGN_OUT',
    SIGN_ERROR: 'SIGN_ERROR',
    SIGN_LOADING: 'SIGN_LOADING',
  
    CATEGORY_ALL: 'CATEGORY_ALL',
    CATEGORY_LOADING: 'CATEGORY_LOADING',
    CATEGORY_CREATE: 'CATEGORY_CREATE',
    CATEGORY_UPLOAD: 'CATEGORY_UPLOAD',
    CATEGORY_EDIT: 'CATEGORY_EDIT'
  }
  
  export default Types
  