const Types = {
  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP',
  SIGN_OUT: 'SIGN_OUT',
  SIGN_ERROR: 'SIGN_ERROR',
  SIGN_LOADING: 'SIGN_LOADING',

  CATEGORY_ALL: 'CATEGORY_ALL',
  CATEGORY_LOADING: 'CATEGORY_LOADING',
  CATEGORY_CREATE: 'CATEGORY_CREATE',
  CATEGORY_UPLOAD: 'CATEGORY_UPLOAD',
  CATEGORY_EDIT: 'CATEGORY_EDIT',

  FORNECEDOR_ALL: 'FORNECEDOR_ALL',
  FORNECEDOR_LOADING: 'FORNECEDOR_LOADING',
  FORNECEDOR_CREATE: 'FORNECEDOR_CREATE',
  FORNECEDOR_UPLOAD: 'FORNECEDOR_UPLOAD',
  FORNECEDOR_EDIT: 'FORNECEDOR_EDIT',
  FORNECEDOR_STATUS: 'FORNECEDOR_STATUS'
}

export default Types
