const Types = {
  SIGN_IN: 'SIGN_IN',
  SIGN_UP: 'SIGN_UP',
  SIGN_OUT: 'SIGN_OUT',
  SIGN_ERROR: 'SIGN_ERROR',
  SIGN_LOADING: 'SIGN_LOADING',

  CATEGORY_LOADING: 'CATEGORY_LOADING',
  CATEGORY_ALL: 'CATEGORY_ALL',
  CATEGORY_CREATE: 'CATEGORY_CREATE',
  CATEGORY_UPDATE: 'CATEGORY_UPDATE',
  CATEGORY_EDIT: 'CATEGORY_EDIT',
  CATEGORY_ID: 'CATEGORY_ID',
  CATEGORY_UPLOAD: 'CATEGORY_UPLOAD',

  PROVIDER_LOADING: 'PROVIDER_LOADING',
  PROVIDER_ALL: 'PROVIDER_ALL',
  PROVIDER_CREATE: 'PROVIDER_CREATE',
  PROVIDER_UPDATE: 'PROVIDER_UPDATE',
  PROVIDER_EDIT: 'PROVIDER_EDIT',
  PROVIDER_STATUS: 'PROVIDER_STATUS',
  PROVIDER_PRODUCTS: 'PROVIDER_PRODUCTS',
  PROVIDER_PRODUCT_ID: 'PROVIDER_PRODUCT_ID',
  PROVIDER_SELECT: 'PROVIDER_SELECT',
  PROVIDER_ALL_SEARCH: 'PROVIDER_ALL_SEARCH',
  PROVIDER_LIKE_LIST: 'PROVIDER_LIKE_LIST',
  PROVIDER_UPLOAD: 'PROVIDER_UPLOAD',

  PRODUCT_LOADING: 'PRODUCT_LOADING',
  PRODUCT_ALL: 'PRODUCT_ALL',
  PRODUCT_CREATE: 'PRODUCT_CREATE',
  PRODUCT_EDIT: 'PRODUCT_EDIT',
  PRODUCT_UPDATE: 'PRODUCT_UPDATE',
  PRODUCT_REMOVE: 'PRODUCT_REMOVE',
  PRODUCT_UPLOAD: 'PRODUCT_UPLOAD',

  CLIENT_LOADING: 'CLIENT_LOADING',
  CLIENT_ALL: 'CLIENT_ALL',
  CLIENT_LIKE: 'CLIENT_LIKE',
  CLIENT_LIKE_LOADING: 'LIKE_LOADING'
}

export default Types
